"""HTML document shell for exported reports."""

from __future__ import annotations

import html

from clible.ui.export.css import HTML_EXPORT_THEME

# Restricts the exported HTML to inline styles only — no scripts, frames, or external fetches.
# This prevents browsers from generating security warnings when opening exported files
# via the file:// protocol.
_HTML_CSP = "default-src 'none'; style-src 'unsafe-inline';"


def render_html_document(title: str, content_fragments: list[str]) -> str:
    """Wrap body fragments in the shared HTML shell."""
    csp_meta = f'<meta http-equiv="Content-Security-Policy" content="{_HTML_CSP}">'
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        + csp_meta
        + f"<title>{html.escape(title)}</title>{HTML_EXPORT_THEME}</head>"
        "<body><main class='page-shell'>"
        + "".join(content_fragments)
        + "<p class='footer-note'>Generated by clible export • Enjoy the study workflow.</p>"
        + "</main></body></html>"
    )
