"""HTML document shell for exported reports."""

from __future__ import annotations

import html

from clible.ui.export.css import HTML_EXPORT_THEME


def render_html_document(title: str, content_fragments: list[str]) -> str:
    """Wrap body fragments in the shared HTML shell."""
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        f"<title>{html.escape(title)}</title>{HTML_EXPORT_THEME}</head>"
        "<body><main class='page-shell'>"
        + "".join(content_fragments)
        + "<p class='footer-note'>Generated by clible export • Enjoy the study workflow.</p>"
        + "</main></body></html>"
    )
